name: Node Scan Workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t vulnerable-node ./vulnerable-node 
    
    - name: Scan with Docker Scout
      uses: docker/scout-action@v1
      with:
        command: cves
        exit-code: 2

    - name: Scan with Trivy
      uses: aquasecurity/trivy-action@0.29.0 
      with:
        image-ref: vulnerable-node
