name: PHP Scan Workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t vulnerable-php ./vulnerable-php
    
    - name: Scan with Docker Scout
      uses: docker/scout-action@v1
      with:
        command: cves,recommendations
        sarif-file: sarif.output.json
        summary: true

    - name: Scan with Trivy
      uses: aquasecurity/trivy-action@0.29.0 
      with:
        image-ref: vulnerable-php
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

